# Generated by Django 4.2.2 on 2023-07-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('EP', 'En Preparacion'), ('ED', 'En Despacho'), ('E', 'Entregado')], default='P', max_length=2),
        ),
    ]
