# Generated by Django 4.2.2 on 2023-07-07 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor del Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
