# Generated by Django 4.2.2 on 2023-07-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pedido_author_pedido_cancelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='author',
        ),
    ]
